// Mocks generated by Mockito 5.4.6 from annotations
// in gamer_rec/test/unit/recording/recording_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i2;
import 'package:gamer_rec/core/errors/failures.dart' as _i7;
import 'package:gamer_rec/features/recording/domain/entities/recording_config.dart'
    as _i3;
import 'package:gamer_rec/features/recording/domain/usecases/recording_controls.dart'
    as _i8;
import 'package:gamer_rec/features/recording/domain/usecases/start_recording.dart'
    as _i5;
import 'package:gamer_rec/features/settings/domain/entities/device_capabilities.dart'
    as _i4;
import 'package:gamer_rec/features/settings/domain/repositories/settings_repository.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRecordingConfig_1 extends _i1.SmartFake
    implements _i3.RecordingConfig {
  _FakeRecordingConfig_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeviceCapabilities_2 extends _i1.SmartFake
    implements _i4.DeviceCapabilities {
  _FakeDeviceCapabilities_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StartRecordingUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockStartRecordingUseCase extends _i1.Mock
    implements _i5.StartRecordingUseCase {
  MockStartRecordingUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> call(_i3.RecordingConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [config],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #call,
            [config],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);
}

/// A class which mocks [StopRecordingUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockStopRecordingUseCase extends _i1.Mock
    implements _i8.StopRecordingUseCase {
  MockStopRecordingUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);
}

/// A class which mocks [PauseRecordingUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPauseRecordingUseCase extends _i1.Mock
    implements _i8.PauseRecordingUseCase {
  MockPauseRecordingUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);
}

/// A class which mocks [ResumeRecordingUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResumeRecordingUseCase extends _i1.Mock
    implements _i8.ResumeRecordingUseCase {
  MockResumeRecordingUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i9.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.RecordingConfig> loadConfig() => (super.noSuchMethod(
        Invocation.method(
          #loadConfig,
          [],
        ),
        returnValue:
            _i6.Future<_i3.RecordingConfig>.value(_FakeRecordingConfig_1(
          this,
          Invocation.method(
            #loadConfig,
            [],
          ),
        )),
      ) as _i6.Future<_i3.RecordingConfig>);

  @override
  _i6.Future<void> saveConfig(_i3.RecordingConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveConfig,
          [config],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.DeviceCapabilities> getDeviceCapabilities() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDeviceCapabilities,
          [],
        ),
        returnValue:
            _i6.Future<_i4.DeviceCapabilities>.value(_FakeDeviceCapabilities_2(
          this,
          Invocation.method(
            #getDeviceCapabilities,
            [],
          ),
        )),
      ) as _i6.Future<_i4.DeviceCapabilities>);
}
